### PR TITLE
Buddy deploy

### PR DESCRIPTION
**Pull request by palmiak**
### Description 📖

Adds documentation about deploying Iles using Buddy

### CODE REVIEW

**Comment by ElMassimo** [comment]
Hi Maciek!

It doesn't seem like any of the instructions for deploying with Buddy are specific to îles.

I'd be ok mentioning Buddy in this section if there was a demo project to link to, and we trim down the text to the specifics (Netlify, Vercel, and Cloudflare have two paragraphs each).

**Comment by palmiak** [comment]
Hi @ElMassimo 

So to get everything straight, because I would love to correct it, so you add this:
- it's too long - here is the problem, Buddy can either work in GUI mode (which most users use) or in YAML. If describing the GUI it obviously has to be a bit longer rather than two sentences. Althought I can trim it down to be more concise.
- instead of a demo project I can also add a `buddy.yaml` - that users can add to their projects to initialize the basic actions

**Comment by ElMassimo** [comment]
The intent of the _Deployment_ section is not to explain how other tools work, but how to configure anything specific to an îles site.

If an îles site would work out of the box with Buddy, then the section should be empty, and simply mention that Buddy can be used to deploy îles sites without additional configuration (rather than describe what Buddy is and how it works).

**Comment by palmiak** [comment]
Got it. I will give another go tomorrow. Thank you for your patience 🙂

niedz., 28 sie 2022, 18:54 użytkownik Máximo Mussini <
***@***.***> napisał:

**Pull request closed without merging**
