### PR TITLE
Document limitation on combining islands with interactive Vue logic

### PR DESCRIPTION
**Pull request by lucperkins**
### Description 📖

Provides some documentation around hydration and islands that may benefit others that run into the stumbling block discussed [here](https://github.com/ElMassimo/iles/discussions/217).

### CODE REVIEW

**Review by ElMassimo — COMMENTED** [review]
We should clarify that the problem is not "mixing" islands *and* interactive Vue logic.

Any logic outside islands will be executed once, when rendering. In some cases that's desirable, think about a product catalog that only displays a slider when there are images for the product, but skips it if not.

In this example, `v-if="drawerIsOpen"` is outside an island, so it will be evaluated once. `Drawer` being an island or not __does not__ make a difference as to why clicking the button "wouldn't work".

To avoid confusion we should simplify the example, as the core idea is: if it's interactive, it should be inside an island (or client script). Any code outside islands will run only at build time.

**Comment by lucperkins** [comment]
@ElMassimo Awesome, great insights. I'll update to reflect this.

**Comment by ouuan** [comment]
I don't think we need more documentation to "clarify" that interactive logic should be inside an island, as that is what an island *is*. I mean, a place where interactive logic happens on the client side, is the definition of an island, not some deeply hidden property of an island.

According to #217, I think what needs to be clarified is that interactive logic outside of an island works in dev mode. The difference between the dev preview and the production build needs to be taken care of.

**Comment by ElMassimo** [comment]
> that is what an island is

Agreed. The documentation should explain this in the first sections (_Development_ and _Hydration_) without assuming prior knowledge. I'll improve these sections accordingly.

> ...what needs to be clarified is that interactive logic outside of an island works in dev mode

💯 

And ideally [prevent that](https://github.com/ElMassimo/iles/discussions/217#discussioncomment-4698719):

> îles should log a warning if it detects you are adding listeners in non-island components

**Pull request closed without merging**
